window.GRADPATH_ADVICE=[
{ids:[101],school:'MIT Sloan',title:'MFin 招生团队如何看申请',points:['整体评估，不机械地把任何单一材料设为最高权重。','重点看学术表现、个人成就、沟通能力，以及对金融与影响力的持续投入。','不限定本科专业；微积分、统计、线性代数、概率和 Python 有助于证明准备度。','工作经验不是硬性要求，许多应届申请者已有实习。'],source:'https://mitsloan.mit.edu/mfin/admissions/common-questions',label:'项目官方 FAQ'},
{ids:[103],school:'Princeton BCF',title:'MFin 招生端强调的准备度',points:['最强申请者通常展现多方面的扎实能力，而非只在单项上突出。','需要完成数学能力评估；GRE/GMAT 可选。','三封推荐信中可包含一封雇主推荐，但应具体说明能力与贡献。'],source:'https://bcf.princeton.edu/academic-programs/master-in-finance/common-questions/',label:'项目官方 FAQ'},
{ids:[111],school:'London Business School',title:'MFA 招生团队公开建议',points:['典型申请者为毕业两年内、全职工作经验不超过两年。','官方参考为英国 2:1 或 GPA 3.3+，同时重视量化能力。','实习并非硬性要求，但相关经历能增强申请；GMAT/GRE 或 CFA Level I 可证明准备度。'],source:'https://admissionsblog.london.edu/masters-in-financial-analysis-why-you-should-apply-and-what-we-look-for/',label:'学校招生博客'},
{ids:[301],school:'UC Berkeley Haas',title:'MFE 的量化背景信号',points:['班级画像显示学生常来自数学、统计、工程、计算机、经济与金融。','应把量化课程、编程能力和相关工作成果写成可核验的证据。'],source:'https://mfe.haas.berkeley.edu/admissions/faq',label:'项目官方 FAQ'},
{ids:[303],school:'Carnegie Mellon MSCF',title:'MSCF 对候选人的直接建议',points:['重视数学深度、量化金融理解、清晰职业目标，以及沟通和团队能力。','可通过有学分的先修课补短板，并以金融实习、研究、市场跟踪或模拟交易建立相关性。','相关全职经验更佳但非必需；项目要求 GRE/GMAT，并更推荐 GRE。'],source:'https://www.cmu.edu/mscf/about-us/faq.html',label:'项目官方 FAQ'}];

window.GRADPATH_CASES=[
{ids:[101],school:'MIT Sloan',program:'Master of Finance',year:'2023',type:'官方班级画像',trust:'高',gpa:'平均 3.83（采用 4.0 制院校）',test:'GRE Q 中位数 169；中间 80% 为 158–170',experience:'平均 12 个月（含实习）',background:'80% 本科为 STEM；86% 在校期间申请',outcome:'127 人入学班级',source:'https://mitsloan.mit.edu/sites/default/files/inline-files/MFin-FactSheet-2023.pdf'},
{ids:[102],school:'Yale SOM',program:'MMS in Asset Management',year:'Class of 2026',type:'官方班级画像',trust:'高',gpa:'中间 80% 为 3.72–4.00（仅统计采用 4.0 制的美国院校）',test:'GRE Q 中间 80% 为 165–170；GMAT Focus 为 647–715',experience:'官网未披露可直接比较的单一均值',background:'66 人；77% 外籍；9% 为联合 MBA 学生',outcome:'已入学班级画像',source:'https://som.yale.edu/programs/mms-asset-management/student-experience/class-profile-class-2026'},
{ids:[301],school:'UC Berkeley Haas',program:'Master of Financial Engineering',year:'Entering 2025',type:'官方班级画像',trust:'高',gpa:'美国院校平均 GPA 3.77',test:'GRE Q 平均百分位 91%；V 79%',experience:'平均工作经验 2.47 年',background:'84 人；主修集中于计算机、工程、数学、金融与统计',outcome:'已入学班级画像',source:'https://mfe.haas.berkeley.edu/admissions/class-profile'},
{ids:[303],school:'Carnegie Mellon',program:'MS in Computational Finance',year:'Fall 2025',type:'官方班级画像',trust:'高',gpa:'平均 3.86',test:'平均 GRE 169Q / 161V',experience:'77% 无全职工作经验',background:'1,051 名申请者；108 人入学；52% 数学/统计',outcome:'已入学班级画像；不能视作个人录取概率',source:'https://www.cmu.edu/mscf/admissions/class-profile.html'},
{ids:[111],school:'London Business School',program:'Masters in Financial Analysis',year:'当前公开口径',type:'官方目标画像',trust:'高',gpa:'英国 2:1 或 GPA 3.3+ 为官方参考',test:'竞争力较强的 GMAT/GRE，或 CFA Level I',experience:'毕业后 0–2 年；实习可增值但非硬性要求',background:'强调量化能力与可证明的金融兴趣',outcome:'目标画像，并非录取案例',source:'https://www.london.edu/masters-degrees/masters-in-financial-analysis/faqs?entry=true'},
{ids:[301,303],school:'公开社区',program:'MFE 先修课讨论',year:'公开帖',type:'申请者自报',trust:'低',gpa:'约 3.9（自报）',test:'GRE 170Q / 169V（自报）',experience:'约 6 年金融/资管经历（自报）',background:'数学、统计与编程课程；主要讨论先修课适配',outcome:'录取结果未披露，不作为成功案例',source:'https://www.reddit.com/r/gradadmissions/comments/ebnb5e/uc_berkeley_mfe_prerequisites/'},
{ids:[301,303],school:'公开社区',program:'MFE 选校匹配讨论',year:'公开帖',type:'申请者自报',trust:'低',gpa:'8/10（自报）',test:'GRE 331：168Q / 163V（自报）',experience:'数据工程、金融科技量化风险、资管量化组合（自报）',background:'计算机 + 应用数学；预计入学时约 4 年经验',outcome:'结果未披露，仅供理解背景表达',source:'https://www.reddit.com/r/quant/comments/x2dn39/mfe_schools_fit_for_my_profile/'}];
